#!/usr/bin/env python3
"""Generate Gazebo Harmonic SDF worlds + JSON manifests from the shared
world definitions in sim/ccsim/world.py, so Gazebo and the 2D surrogate use
the same layouts.

  python3 src/cc_gazebo/scripts/generate_worlds.py [--seed 1000] [--out src/cc_gazebo/worlds]

Each world gets <name>.sdf and <name>.json (start, goal, object classes and
footprints, actor trajectories, kidnap event). The eval harness and the
oracle detector read the manifest; the stack itself never does.
"""
import argparse
import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parents[3] / "sim"))

from ccsim.world import WORLD_NAMES, make_world  # noqa: E402

WALL_H, WALL_T = 2.0, 0.1
GLASS_VIS_FLAG = 2   # LiDAR visibility_mask excludes this bit (see cc_description/urdf/gazebo.xacro)
ACTOR_MESH = "https://fuel.gazebosim.org/1.0/Mingfei/models/actor/tip/files/meshes/walk.dae"

HEADER = """<?xml version="1.0"?>
<!-- GENERATED by cc_gazebo/scripts/generate_worlds.py from sim/ccsim/world.py (seed {seed}). Do not edit. -->
<sdf version="1.9">
  <world name="{name}">
    <physics name="1ms" type="ignore">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
    <scene><ambient>0.6 0.6 0.6 1</ambient><background>0.8 0.85 0.9 1</background><shadows>false</shadows></scene>
{gui}    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <direction>-0.4 0.2 -0.9</direction>
    </light>
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>200 200</size></plane></geometry>
          <!-- polished floor -->
          <surface><friction><ode><mu>0.6</mu><mu2>0.6</mu2></ode></friction></surface>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>200 200</size></plane></geometry>
          <material><ambient>0.85 0.85 0.82 1</ambient><diffuse>0.85 0.85 0.82 1</diffuse></material>
        </visual>
      </link>
    </model>
"""


HIDDEN = ('<gz-gui><property key="resizable" type="bool">false</property>'
          '<property key="width" type="double">5</property><property key="height" type="double">5</property>'
          '<property key="state" type="string">floating</property>'
          '<property key="showTitleBar" type="bool">false</property></gz-gui>')


def gui_block(start):
    """Gazebo GUI config. Same panels as the default layout, but the 3D view
    starts 3.5 m behind the robot and 3 m up, looking along its heading
    (the default camera can start far from the world)."""
    x, y, yaw = start
    cx, cy = x - 3.5 * math.cos(yaw), y - 3.5 * math.sin(yaw)
    hidden = "\n".join(
        f'      <plugin filename="{f}" name="{n}">{HIDDEN}</plugin>'
        for f, n in [("GzSceneManager", "Scene Manager"), ("InteractiveViewControl", "Interactive view control"),
                     ("CameraTracking", "Camera Tracking"), ("MarkerManager", "Marker manager"),
                     ("SelectEntities", "Select Entities"), ("Spawn", "Spawn Entities"),
                     ("VisualizationCapabilities", "Visualization Capabilities")])
    return f"""    <gui fullscreen="0">
      <plugin filename="MinimalScene" name="3D View">
        <gz-gui><title>3D View</title><property type="bool" key="showTitleBar">false</property>
          <property type="string" key="state">docked</property></gz-gui>
        <engine>ogre2</engine>
        <scene>scene</scene>
        <ambient_light>0.4 0.4 0.4</ambient_light>
        <background_color>0.8 0.85 0.9</background_color>
        <camera_pose>{cx:.2f} {cy:.2f} 3.0 0 0.6 {yaw:.3f}</camera_pose>
        <camera_clip><near>0.1</near><far>500</far></camera_clip>
      </plugin>
{hidden}
      <plugin filename="WorldControl" name="World control">
        <gz-gui><title>World control</title><property type="bool" key="showTitleBar">false</property>
          <property type="bool" key="resizable">false</property><property type="double" key="height">72</property>
          <property type="double" key="z">1</property><property type="string" key="state">floating</property>
          <anchors target="3D View"><line own="left" target="left"/><line own="bottom" target="bottom"/></anchors></gz-gui>
        <play_pause>true</play_pause><step>true</step><start_paused>false</start_paused><use_event>true</use_event>
      </plugin>
      <plugin filename="WorldStats" name="World stats">
        <gz-gui><title>World stats</title><property type="bool" key="showTitleBar">false</property>
          <property type="bool" key="resizable">false</property><property type="double" key="height">110</property>
          <property type="double" key="width">290</property><property type="double" key="z">1</property>
          <property type="string" key="state">floating</property>
          <anchors target="3D View"><line own="right" target="right"/><line own="bottom" target="bottom"/></anchors></gz-gui>
        <sim_time>true</sim_time><real_time>true</real_time><real_time_factor>true</real_time_factor><iterations>true</iterations>
      </plugin>
      <plugin filename="EntityTree" name="Entity tree"></plugin>
      <plugin filename="ComponentInspector" name="Component inspector"></plugin>
    </gui>
"""


def box_model(name, x, y, z, yaw, sx, sy, sz, rgba, static=True, extra_visual=""):
    return f"""    <model name="{name}">
      <static>{str(static).lower()}</static>
      <pose>{x:.4f} {y:.4f} {z:.4f} 0 0 {yaw:.4f}</pose>
      <link name="link">
        <collision name="collision"><geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry></collision>
        <visual name="visual">
          <geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry>
          <material><ambient>{rgba}</ambient><diffuse>{rgba}</diffuse></material>{extra_visual}
        </visual>
      </link>
    </model>
"""


def segment_box(name, seg, thickness, height, rgba, extra_visual=""):
    x1, y1, x2, y2 = seg
    length = math.hypot(x2 - x1, y2 - y1)
    return box_model(name, (x1 + x2) / 2, (y1 + y2) / 2, height / 2, math.atan2(y2 - y1, x2 - x1),
                     length + thickness, thickness, height, rgba, extra_visual=extra_visual)


def cart_model(name, o):
    """Cart: thin legs cross the LiDAR plane, the body and handle sit above it."""
    c, s = math.cos(o.yaw), math.sin(o.yaw)
    hx, hy = o.sx / 2 - 0.04, o.sy / 2 - 0.04
    legs = ""
    for k, (a, b) in enumerate([(hx, hy), (-hx, hy), (-hx, -hy), (hx, -hy)]):
        legs += f"""        <collision name="leg{k}"><pose>{a:.3f} {b:.3f} 0.15 0 0 0</pose><geometry><cylinder><radius>0.02</radius><length>0.30</length></cylinder></geometry></collision>
        <visual name="leg{k}_v"><pose>{a:.3f} {b:.3f} 0.15 0 0 0</pose><geometry><cylinder><radius>0.02</radius><length>0.30</length></cylinder></geometry></visual>
"""
    return f"""    <model name="{name}">
      <static>true</static>
      <pose>{o.x:.4f} {o.y:.4f} 0 0 0 {o.yaw:.4f}</pose>
      <link name="link">
{legs}        <collision name="body"><pose>0 0 0.5 0 0 0</pose><geometry><box><size>{o.sx:.3f} {o.sy:.3f} 0.4</size></box></geometry></collision>
        <visual name="body_v"><pose>0 0 0.5 0 0 0</pose><geometry><box><size>{o.sx:.3f} {o.sy:.3f} 0.4</size></box></geometry>
          <material><ambient>0.7 0.7 0.75 1</ambient><diffuse>0.7 0.7 0.75 1</diffuse></material></visual>
        <collision name="handle"><pose>{-o.sx / 2:.3f} 0 0.9 0 0 0</pose><geometry><box><size>0.03 {o.sy:.3f} 0.03</size></box></geometry></collision>
        <visual name="handle_v"><pose>{-o.sx / 2:.3f} 0 0.9 0 0 0</pose><geometry><box><size>0.03 {o.sy:.3f} 0.03</size></box></geometry></visual>
      </link>
    </model>
"""


def actor_xml(name, a):
    """Ping-pong walk starting at the actor's phase position, looped."""
    x, y, vx, vy = a.state()
    p_a, p_b = a.waypoints[0], a.waypoints[-1]
    forward = (vx * (p_b[0] - p_a[0]) + vy * (p_b[1] - p_a[1])) >= 0
    far, near = (p_b, p_a) if forward else (p_a, p_b)
    pts = [(x, y), tuple(far), tuple(near), (x, y)]
    t, wps = 0.0, []
    for k, (px, py) in enumerate(pts):
        if k > 0:
            t += math.hypot(px - pts[k - 1][0], py - pts[k - 1][1]) / a.speed
        nxt = pts[min(k + 1, len(pts) - 1)] if k < len(pts) - 1 else pts[1]
        yaw = math.atan2(nxt[1] - py, nxt[0] - px)
        wps.append(f"          <waypoint><time>{t:.3f}</time><pose>{px:.3f} {py:.3f} 1.0 0 0 {yaw:.3f}</pose></waypoint>")
    return f"""    <actor name="{name}">
      <skin><filename>{ACTOR_MESH}</filename><scale>1.0</scale></skin>
      <animation name="walking"><filename>{ACTOR_MESH}</filename><interpolate_x>true</interpolate_x></animation>
      <script>
        <loop>true</loop>
        <auto_start>true</auto_start>
        <trajectory id="0" type="walking">
{chr(10).join(wps)}
        </trajectory>
      </script>
    </actor>
"""


def generate(name, seed, out_dir):
    w = make_world(name, seed)
    parts = [HEADER.format(name=name, seed=seed, gui=gui_block(w.start))]
    for k, seg in enumerate(w.walls):
        parts.append(segment_box(f"wall_{k}", seg, WALL_T, WALL_H, "0.75 0.75 0.72 1"))
    glass_extra = f"\n          <transparency>0.8</transparency>\n          <visibility_flags>{GLASS_VIS_FLAG}</visibility_flags>"
    for k, seg in enumerate(w.glass):
        parts.append(segment_box(f"glass_{k}", seg, 0.02, WALL_H, "0.6 0.8 0.9 0.3", extra_visual=glass_extra))
    objects = []
    for k, o in enumerate(w.obstacles):
        nm = f"{o.kind}_{k}"
        if o.kind == "cart":
            parts.append(cart_model(nm, o))
        else:
            rgba = {"pallet": "0.6 0.45 0.25 1", "low_box": "0.8 0.6 0.3 1", "shelf": "0.4 0.4 0.45 1"}[o.kind]
            parts.append(box_model(nm, o.x, o.y, o.height / 2, o.yaw, o.sx, o.sy, o.height, rgba))
        objects.append({"name": nm, "kind": o.kind, "class": o.cls, "x": o.x, "y": o.y, "yaw": o.yaw,
                        "size_x": o.sx, "size_y": o.sy, "height": o.height})
    actors = []
    for k, a in enumerate(w.actors):
        parts.append(actor_xml(f"person_{k}", a))
        actors.append({"name": f"person_{k}", "waypoints": a.waypoints.tolist(), "speed": a.speed,
                       "phase": a.phase, "radius": a.radius})
    parts.append("  </world>\n</sdf>\n")
    (out_dir / f"{name}.sdf").write_text("".join(parts))
    manifest = {
        "world": name, "seed": seed, "bounds": list(w.bounds),
        "start": [float(v) for v in w.start], "goal": [float(v) for v in w.goal], "timeout": w.timeout,
        "walls": w.walls.tolist(), "glass": w.glass.tolist(), "objects": objects, "actors": actors,
        "kidnap": None if w.kidnap is None else {"time": w.kidnap[0], "pose": [float(v) for v in w.kidnap[1]]},
    }
    (out_dir / f"{name}.json").write_text(json.dumps(manifest, indent=2))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--seed", type=int, default=1000)
    p.add_argument("--out", default=str(HERE.parents[1] / "worlds"))
    a = p.parse_args()
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    for name in WORLD_NAMES:
        generate(name, a.seed, out)
        print("wrote", out / f"{name}.sdf")


if __name__ == "__main__":
    main()
